### ISSUE TITLE
Local denial of service - triggering SIGPIPE in the deamon

### ISSUE THREAD

**Issue by thorkill** [lemoer/bpfcountd#1]
Local user with access to the UNIX Socket can cause bpfcountd to exit with SIGPIPE simply by connecting to the socket and close it without reading any data causing local denial of service.

Tested on Arch Linux / x86-64.

```
(gdb) r  -i wls1 -f ./filters.example
Starting program: [...]/git-github/bpfcountd/bpfcountd -i wls1 -f ./filters.example
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Device: wls1
id: arp-req; bpf: "arp[6:2] == 1";
id: arp-rep-norm; bpf: "not ether broadcast and arp[6:2] == 2";
id: arp-rep-grat; bpf: "ether broadcast and arp[6:2] == 2 and ether src 00:26:c6:12:6f:a4";

Program received signal SIGPIPE, Broken pipe.
0x00007ffff78d7c7d in send () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff78d7c7d in send () from /usr/lib/libc.so.6
#1  0x00000000004019cb in usock_sendstr (client_sock=5, str=0x7fffffffe5a0 "arp-rep-grat:0:0\n") at usock.c:45
#2  0x000000000040178b in main (argc=5, argv=0x7fffffffeae8) at main.c:158

```

You can reproduce the bug with this code:

[sock.c.txt](https://github.com/lemoer/bpfcountd/files/270607/sock.c.txt)

```
>> ./sock ../test.sock 
prepare socket ... done
connecting to bpfcountd ... done
trigger SIGPIPE in bpfcountd ... done
testing if bpfcountd died ... yes rawr!
```

**Comment by lemoer** [comment]
Thanks for reporting.
